alias gadd='git add'
alias gcommit='git commit'
alias glog='git log'
alias gmerge='git merge'
alias gpull='git pull'
alias gpush='git push'
alias lsx='ls -Gh'
alias cpx='cp -i'
alias md='mkdir'
alias mvx='mv -i'
alias ren='mv -i'
alias gco='gcommit -am "bugs" && gpull'
alias gcommitall='gcommit -am'
alias glograph='git log --pretty=format:"%h%x09%an%x09%d%x09%s" --graph'
